name: Check lints and test on push
on: [push]
jobs:
  check-and-test-stable:
    name: Check and test with stable toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets

  fmt-and-clippy-nightly:
    name: Format and clippy with nightly toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- -D warnings
